# Generated by Django 4.1.1 on 2022-10-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_email_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('postid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.post')),
            ],
        ),
    ]
